#
#	MongoDB Dockerfile
#
FROM ubuntu:14.04

# Import MongoDB public GPG key AND create a MongoDB list file
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
RUN echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | tee /etc/apt/sources.list.d/10gen.list

# Update apt-get sources AND install MongoDB
RUN apt-get update && apt-get install -y mongodb-org

# Create the MongoDB data directory
RUN mkdir -p /data

# Expose port 27017 from the container to the host
EXPOSE 27017

# start MOngodb instance with PORT 27017 and STORAGE path as data folder 
CMD [ "mongod", "--dbpath", "data" ]
